# Generated by Django 4.2.1 on 2023-05-21 21:55

import custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('image', models.ImageField(max_length=500, storage=custom_storage.S3ImageStorage(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TempImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_file', models.ImageField(upload_to='tempImageFiles')),
            ],
        ),
    ]
